name: buildPOIapi #name of the workflow

on:
  push: #when we push any changes to the POI code, triggers workflow to run
    branches: [ master ]
    paths: 
      - 'apis/poi/**'
      - '.github/workflows/dotnet.yml'
  
  pull_request:  #when we pull any changes to the POI code, triggers workflow to run
     branches: [ master ]
     paths: 
      - 'apis/poi/**'
      - '.github/workflows/dotnet.yml'

jobs: #jobs that we need to run to 1: Build & Test the Code   2: create a work item on failure.
  build-and-Test: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./apis/poi/web/poi.csproj #added to run the job
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: The Build has failed #start of errorhandling
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
          OrganizationName: "openhackdevopst2harachum"
          PAT: "PAT"
          ProjectName: "OpenHackDevOpsT2"
          AreaPath: "OpenHackDevOpsT2\\Automation"
          IterationPath: "OpenHackDevOpsT2\\Sprint 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "error.yml"
      env:
          PAT: ${{ secrets.PAT}}
          GithubToken: ${{ secrets.githubtoken}}
